version = 0.1

[default.deploy.parameters]
stack_name = "dailybluechipstocks-backend"
resolve_s3 = true
s3_prefix = "dailybluechipstocks-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolId=\"us-east-1_gfVsnIELk\" CognitoAppClientId=\"71osdnkvspv2fgoeirmm6fmee6\" FrontendOrigin=\"http://localhost:5173\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
